#!/usr/bin/env python3
"""Compare two PDFs page by page and fail if any pixel differs.

Why this exists
---------------
`slideflare export` renders the deck into a surface nobody is looking at — an
offscreen GTK window, a hidden HWND, a macOS window parked past the edge of
every display. Every one of those arrangements exists to keep the engine
treating the content as visible, because an engine that decides otherwise does
not error: it lays replaced elements out at zero height, the deck measures
short, and every slide prints over-sized and clipped at exit code 0. A smoke
test that only checks the file is non-empty passes that with room to spare.

So CI renders the same deck twice on the same runner — once the normal
windowless way, once with `SLIDEFLARE_EXPORT_WINDOW=visible`, which puts the
old real window back — and requires the two to be pixel-for-pixel identical.
A reference generated by the same fonts, the same engine and the same machine
is the only reference worth having here; a committed image could not be, since
text rasterizes differently on all three platforms and on any two runner
images.

Why pypdfium2 rather than poppler or ImageMagick
------------------------------------------------
It is a pip wheel with the renderer inside it, so the same two lines of setup
work on all three runners. `pdftoppm` and `magick` would each need a different
package manager per platform, and `choco install poppler` in particular is not
something to hang a release gate on.

Usage:
    pdf-pixel-diff.py A.pdf B.pdf [--dpi 150] [--out DIR]

Exits 0 when every page matches, 1 otherwise. With `--out`, the first differing
page is written there as three PNGs (a, b, and their difference) so a CI
failure can be looked at rather than only read about.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import pypdfium2 as pdfium
    from PIL import Image, ImageChops
except ImportError as exc:  # pragma: no cover - a setup failure, not a test one
    sys.exit(f"missing dependency: {exc}. Install with: pip install pypdfium2 pillow")


def render(path: Path, dpi: int) -> list[Image.Image]:
    """Rasterize every page of `path` to RGB at `dpi`."""
    document = pdfium.PdfDocument(str(path))
    try:
        scale = dpi / 72.0
        return [page.render(scale=scale).to_pil().convert("RGB") for page in document]
    finally:
        document.close()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("a", type=Path)
    parser.add_argument("b", type=Path)
    parser.add_argument("--dpi", type=int, default=150)
    parser.add_argument(
        "--out",
        type=Path,
        help="directory to write the first differing page into, for inspection",
    )
    args = parser.parse_args()

    pages_a = render(args.a, args.dpi)
    pages_b = render(args.b, args.dpi)

    if len(pages_a) != len(pages_b):
        print(f"page count differs: {args.a} has {len(pages_a)}, {args.b} has {len(pages_b)}")
        return 1

    if not pages_a:
        print("no pages rendered — the export produced an empty document")
        return 1

    failed = 0
    for index, (page_a, page_b) in enumerate(zip(pages_a, pages_b), start=1):
        if page_a.size != page_b.size:
            print(f"page {index}: size differs, {page_a.size} vs {page_b.size}")
            failed = failed or index
            continue

        difference = ImageChops.difference(page_a, page_b)
        # One entry per channel value present; everything but index 0 is a
        # pixel that differs in that channel.
        differing = sum(
            sum(count for value, count in enumerate(channel.histogram()) if value != 0)
            for channel in difference.split()
        )

        if differing:
            share = differing / (page_a.size[0] * page_a.size[1] * 3)
            print(f"page {index}: {differing} differing channel values ({share:.4%})")
            failed = failed or index
        else:
            print(f"page {index}: identical")

    if not failed:
        print(f"identical ({len(pages_a)} pages @ {args.dpi}dpi)")
        return 0

    if args.out:
        args.out.mkdir(parents=True, exist_ok=True)
        page_a, page_b = pages_a[failed - 1], pages_b[failed - 1]
        page_a.save(args.out / f"page{failed}-a.png")
        page_b.save(args.out / f"page{failed}-b.png")
        if page_a.size == page_b.size:
            ImageChops.difference(page_a, page_b).save(args.out / f"page{failed}-diff.png")
        print(f"wrote page {failed} to {args.out}")

    return 1


if __name__ == "__main__":
    sys.exit(main())
